<?php
return array(
	"v1/register$" => array("User/register_post"),
	"v1/user$" => array("User/detail_get"),
	"v1/user/:id$" => array("User/user_get"),
	"v1/user_binding$" => "User/user_binding",
	"v1/user/check/binding" => "User/chk_ephone_binding",
	"v1/user/phone/binding" => "User/phone_binding",
	"v1/card$" => array("User/card_self_get"),
	"v1/card/:id$" => array("User/card_get"),
	"v1/user/update$" => array("User/update_put"),
	"v1/card/update$" => array("User/card_put"),
	"v1/communities/:uid$" => array("Community/communities_get"),
	"v1/communities$" => array("Community/communities_get"),
	"v1/community/join$" => array("Community/community_join_post"),
	"v1/community/quit$" => array("Community/community_delete"),
	"v1/community/search$" => array("Community/community_search_post"),
	"v1/community/school/:id$" => array("Community/school_get"),
	"v1/community/college/:id$" => array("Community/college_get"),
	"v1/community/major/:id$" => array("Community/major_get"),
	"v1/demand/:id$" => array("Demand2/demand_get"),
	"v1/demands/self/:type/role/:role$" => array("Demand2/demands_get", "self=1"),
	"v1/demands/:type/role/:role$" => array("Demand2/demands_get"),
	"v1/demands/:type/role/:role/page/:page$" => array("Demand2/demands_get"),
	"v1/demands/self/:type/role/:role/page/:page$" => array("Demand2/demands_get", "self=1"),
	"v1/demands/:uid/:type/:role/:page$" => array("Demand2/demand_get"), // 获取指定ID用户的需求列表
	"v1/public/similar/:public_id$" => "Demand2/public_similar",
	"v1/public/similar/:public_id/page/:page$" => "Demand2/public_similar",
	"v1/articles/index$" => array("Information/index_get"),
	"v1/articles/:id/praise$" => array("Information/praise"),
	"v1/articles/:id/comment" => "Information/comment", //回复说说
	"v1/articles/download/:id/:score" => "Information/attr_download", //回复说说
	"v1/article/:id$" => array("Information/article_get"),
	"v1/articles/:type$" => array("Information/articles_get"),
	"v1/articles/self/:type$" => array("Information/articles_get", "self=1"),
	"v1/articles/:type/page/:page$" => array("Information/articles_get"),
	"v1/articles/self/:type/page/:page$" => array("Information/articles_get", "self=1"),
	"v1/accounts/:type$" => array("Account2/account_list_get"),
	"v1/accounts/expire/:expire$" => array("Account2/account_expire_get"),
	"v1/account/cash$" => "Account2/get_cash",
	"v1/orders/:type$" => array("Account2/orders_get"),
	"v1/orders/expire/:expire$" => "Account2/orders_expire",
	"v1/order/:id$" => array("Account2/order_get"),
	"v1/order$" => array("Order/gen_order"), //生成订单
	"vq/order/pay/[:pay_type]" => "Order/pay", //订单支付
	"v1/product/:product_type/:product_id$" => "Account2/product_detail",
    "v1/account/cash_recording/:status/:expire/:page$" => "Account2/cash_recording",
	"v1/account/coin_recording/:expire/:page$" => "Account2/coin_recording",
	"v1/account/available_bankcards$" => "Account2/available_banklist",
		
	"v1/message/list/:type/:page$"=>"Message/message_list",
	//"v1/group$" => "Group/group",
	"v1/demand/search/classifies$" => "Demand2/classifies",
	"v1/demand/search/classifies/:classify_id$" => "Demand2/unified",
	"v1/demand/search/unified/:unified_id$" => "Demand2/unified",
	"v1/demands/by/classify/role/:role/type/:type/classify/:classify_id/unified/:unified_id$" => "Demand2/demand_by_unified",
	"v1/demands/by/classify/role/:role/type/:type/classify/:classify_id/unified/:unified_id/page/:page$" => "Demand2/demand_by_unified",
	"v1/demands/by/school/role/:role/type/:type/province/:province_id/university/:university_id/college/:college_id$" => "Demand2/demand_by_school",
	"v1/demands/by/school/role/:role/type/:type/province/:province_id/university/:university_id/college/:college_id/page/:page$" => "Demand2/demand_by_school",
	"test" => array("Test/index"),
);
